global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: "ENTER YOUR SLACK API URL"
    channel: '#test-alert'
    send_resolved: true
    title: '{{ if eq .Status "firing" }}:fire:{{ else }}:white_check_mark:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.title }} '
    pretext: '{{ .CommonAnnotations.summary }}'
    text:
     >-
      {{ range .Alerts }}
       *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`📊
       *dashboard_url:* {{ .Annotations.dashboard_link }}
       *Description:* {{ .Annotations.description }}
       *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
      {{ end }}
